### ISSUE TITLE
Nanopore_analysis.sh is missing

### ISSUE THREAD

**Issue by analeigh-gui** [genometube/HISOFA-seq#1]
Hi! I couldn't find Nanopore_analysis.sh in the repo. Is it still available?

**Comment by genometube** [comment]
Hi, yujuan

I am sorry that the file Nanopore_analysis.sh was broken in upload file. I have uploaded the Nanopore_analysis.sh in main repo. Also, the miss python script I have also uploaded. Thanks for your interest.
